### ISSUE TITLE
[Fixed] The Rift with You will Die Tick Crash

### ISSUE THREAD

**Issue by Peach774** [xFyreStorm/Fyres-Modjam-Entry#1]
java.lang.ArrayIndexOutOfBoundsException: 8
    at assets.fyresmodjam.CommonTickHandler.serverTick(CommonTickHandler.java:65)
    at assets.fyresmodjam.CommonTickHandler.tickStart(CommonTickHandler.java:33)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:574)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
occured right after i entered the rift dimension from the mod the rift.

**Comment by xFyreStorm** [comment]
Thanks, I'll take a look at it, I'm doing bug fixes today anyways.

I'm guessing you had the more mobs world disadvantage? Looks like there's was a problem somehow with spawning it to the dimension, I might have to make sure I'm doing everything right. The nether has the same problem.

EDIT: Fixed in latest release.
